apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: postgres-b
data:
  postgresql.conf: |
    listen_addresses = 'localhost'
    port = 5435
    shared_buffers = 128MB
    work_mem = 4MB
    maintenance_work_mem = 32MB
    max_connections = 10
