apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-sidecar
  namespace: kafka
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: sidecar
          image: bmstu-sidecar:latest
          env:
            - name: SERVICE_TYPE
              value: "kafka"
            - name: AUTH_ENABLED
              value: "false"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
