apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-sidecar
  namespace: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-sidecar
  template:
    metadata:
      labels:
        app: postgresql-sidecar
    spec:
      serviceAccountName: default
      containers:
        - name: sidecar
          image: bmstu-sidecar:latest
          env:
            - name: SERVICE_TYPE
              value: "postgresql"
            - name: AUTH_ENABLED
              value: "false"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: service-account-token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
      volumes:
        - name: service-account-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  expirationSeconds: 3600
