apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-a
  namespace: postgres-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-a
  template:
    metadata:
      labels:
        app: postgres-a
    spec:
      serviceAccountName: default
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: postgres
          image: postgres:13-alpine
          env:
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_DB
              value: "appdb"
            - name: POSTGRES_PORT
              value: "5434"
          ports:
            - containerPort: 5434
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
            - name: config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
            - name: init-script
              subPath: init.sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"

        - name: sidecar
          image: ghcr.io/perpetua1g0d/bmstu-diploma/postgres-sidecar:latest # todo: postgres-sidecar
          env:
            - name: SERVICE_NAME
              value: "postgres-a"
            - name: AUTH_ENABLED
              value: "false"
            - name: INIT_TARGET_SERVICE
              value: "postgres-b"
            - name: INIT_SQL_QUERY
              value: "INSERT INTO log (message) VALUES ('Init from A')"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # - name: POSTGRES_HOST
            #   value: "localhost"
            # - name: POSTGRES_PORT
            #   value: "5434"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"

      volumes:
        - name: postgresql-data
          emptyDir: {}
        - name: config
          configMap:
            name: postgresql-config
        - name: init-script
          configMap:
            name: postgres-init-script
