apiVersion: v1
kind: Service
metadata:
  name: postgres-a
  namespace: postgres-a
spec:
  selector:
    app: postgres-a
  ports:
    - name: postgres
      port: 5434
      targetPort: 5434
    - name: sidecar
      port: 8080
      targetPort: 8080
