apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp
  namespace: idp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idp
  template:
    metadata:
      labels:
        app: idp
    spec:
      serviceAccountName: default
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: idp
          image: ghcr.io/perpetua1g0d/bmstu-diploma/idp:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
