apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-b
  namespace: postgres-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-b
  template:
    metadata:
      labels:
        app: postgres-b
    spec:
      serviceAccountName: default
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: postgres
          image: postgres:13-alpine
          env:
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums" # --config-file=/etc/postgresql/postgresql.conf
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_DB
              value: "appdb"
            - name: POSTGRES_PORT
              value: "5435"
          ports:
            - containerPort: 5435
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
            - name: config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
            - name: init-script
              subPath: init.sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
            - name: shared-env
              mountPath: /etc/postgres-env
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - |
                    echo $POSTGRES_USER > /etc/postgres-env/POSTGRES_USER
                    echo $POSTGRES_PASSWORD > /etc/postgres-env/POSTGRES_PASSWORD
                    echo $POSTGRES_DB > /etc/postgres-env/POSTGRES_DB
                    echo $POSTGRES_HOST > /etc/postgres-env/POSTGRES_HOST
                    echo $POSTGRES_PORT > /etc/postgres-env/POSTGRES_PORT
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"

        - name: sidecar
          image: ghcr.io/perpetua1g0d/bmstu-diploma/postgres-sidecar:latest
          volumeMounts:
            - name: shared-env
              mountPath: /etc/postgres-env
          env:
            - name: SERVICE_NAME
              value: "postgres-b"
            - name: SIGN_AUTH_ENABLED
              value: "true"
            - name: VERIFY_AUTH_ENABLED
              value: "true"
            - name: INIT_TARGET_SERVICE
              value: "postgres-a"
            - name: INIT_SQL_QUERY
              value: "INSERT INTO log (message) VALUES ('Init from B')"

            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # - name: POSTGRES_HOST
            #   value: "localhost"
            # - name: POSTGRES_PORT
            #   value: "5434"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"

      volumes:
        - name: postgresql-data
          emptyDir: {}
        - name: config
          configMap:
            name: postgresql-config
        - name: init-script
          configMap:
            name: postgres-init-script
            items:
              - key: init.sql
                path: init.sql
                mode: 0644
        - name: shared-env
          emptyDir: {}
