apiVersion: apps/v1
kind: Deployment
metadata:
  name: talos
  namespace: talos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talos
  template:
    metadata:
      labels:
        app: talos
    spec:
      containers:
        - name: placeholder
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: talos
  namespace: talos
spec:
  selector:
    app: talos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
