apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        # Основной контейнер PostgreSQL
        - name: postgresql
          image: postgres:13-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_DB
              value: "appdb"
          ports:
            - containerPort: 5434
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
            - name: config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

        # Sidecar-контейнер
        - name: sidecar
          image: ghcr.io/perpetua1g0d/bmstu-diploma/sidecar:latest
          env:
            - name: SERVICE_TYPE
              value: "postgresql"
            - name: POSTGRES_HOST
              value: "localhost"
            - name: POSTGRES_PORT
              value: "5434"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"

      volumes:
        - name: postgresql-data
          emptyDir: {}
        - name: config
          configMap:
            name: postgresql-config

      serviceAccountName: default
      imagePullSecrets:
        - name: ghcr-secret
