apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:13-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: "password"
          ports:
            - containerPort: 5434
          volumeMounts:
            - name: config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
          # resources:
          #   limits:
          #     memory: "256Mi"  # Для основных сервисов
          #     cpu: "250m"
          #   requests:
          #     memory: "128Mi"
          #     cpu: "100m"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: config
          configMap:
            name: postgresql-config
