apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - name: postgresql
      protocol: TCP
      port: 5434
      targetPort: 5434
    - name: sidecar
      protocol: TCP
      port: 8080
      targetPort: 8080
