{
 "title": "bmstu cluster service metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Сервис",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},namespace)"
    }
   },
   { "name": "quantile", "label": "Квантиль", "query": "0.50, 0.95, 0.99" }
  ]
 },
 "panels": [
  {
   "title": "IdP сервер авторизации",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Время выполнения запроса на токен",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum(rate(idp_token_issue_duration_milliseconds_bucket{}[10m])) by (le, client_id, scope, result))",
       "legendFormat": "P$quantile - client={{client_id}} - scope={{scope}} - {{result}}"
      }
     ]
    },
    {
     "title": "Количество выпущенных токенов в секунду",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum(rate(idp_token_issued_total{}[$__rate_interval])) by (client_id, scope, result)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Клиентские метрики авторизации",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Время подписи клиентского запроса токеном",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum(rate(client_token_sign_duration_milliseconds_bucket{service_name=\"$namespace\"}[10m])) by (le, enabled, result, scope))",
       "legendFormat": "P$quantile - sign={{enabled}} - scope={{scope}} - {{result}}"
      }
     ]
    },
    {
     "title": "Время выполнения проверки подписи",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum(rate(client_token_verify_duration_milliseconds_bucket{service_name=\"$namespace\"}[10m])) by (le, enabled, result, scope))",
       "legendFormat": "P$quantile - verify={{enabled}} - scope={{scope}} - {{result}}"
      }
     ]
    },
    {
     "title": "Количество подписей запросов токеном",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum(rate(client_token_sign_requests_total{service_name=\"$namespace\"}[$__rate_interval])) by (enabled, scope, result)",
       "legendFormat": "verify={{enabled}} - scope={{scope}} - {{result}}"
      }
     ]
    },
    {
     "title": "Количество проверок токена входящих запросов",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "sum(rate(client_token_verify_requests_total{service_name=\"$namespace\"}[$__rate_interval])) by (enabled, scope, result)",
       "legendFormat": " sign={{enabled}} - scope={{scope}} - {{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Базовые метрики HTTP запросов",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Размер входящего HTTP-запроса",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum(http_request_size_bytes{service_name=\"$namespace\", quantile=\"$quantile\"}) by (quantile, method, path)",
       "legendFormat": "P$quantile - {{method}} - {{path}}"
      }
     ]
    },
    {
     "title": "Размер HTTP ответов",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum(http_response_size_bytes{service_name=\"$namespace\", quantile=\"$quantile\"}) by (quantile, method, path)",
       "legendFormat": "P{{quantile}} - {{method}} - {{path}}"
      }
     ]
    },
    {
     "title": "Время обработки HTTP запроса",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum(rate(http_request_duration_milliseconds_bucket{service_name=\"$namespace\"}[$__rate_interval])) by (le, method, path))",
       "legendFormat": "P$quantile - {{method}} - {{path}}"
      }
     ]
    },
    {
     "title": "Количество входящих запросов в секунду",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "sum(rate(http_requests_total{service_name=\"$namespace\"}[$__rate_interval])) by (method, path, status)",
       "legendFormat": "{{method}} - {{path}} - {{status}}"
      }
     ]
    }
   ]
  },
  { "title": "Метрики БД", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Время выполнения запросов к БД",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(db_query_duration_milliseconds_bucket{service_name=\"$namespace\"}[$__rate_interval])) by (le, operation)) > 0",
     "legendFormat": "P$quantile - operation={{operation}}"
    }
   ]
  },
  {
   "title": "Количество запросов к БД",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "  sum(rate(db_query_types_total{service_name=\"$namespace\"}[$__rate_interval])) by (type) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Место, занимаемое на диске",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(postgres_db_size_bytes{service_name=\"$namespace\"})/1000 > 0",
     "legendFormat": "Размер"
    }
   ]
  },
  {
   "title": "Количество простаивающих открытых соединений",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(postgres_idle_connections{service_name=\"$namespace\"}) > 0",
     "legendFormat": "Количество соединений"
    }
   ]
  },
  {
   "title": "Количество открытых соединений всего",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(postgres_open_connections{service_name=\"$namespace\"}) > 0",
     "legendFormat": "Количество соединений"
    }
   ]
  }
 ]
}