# кластерные права

apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-ui-sa
  namespace: admin-panel

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmap-editor
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auth-ui-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmap-editor
subjects:
  - kind: ServiceAccount
    name: auth-ui-sa
    namespace: admin-panel
