apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: postgresql
data:
  postgresql.conf: |
    shared_buffers = 128MB
    work_mem = 4MB
    maintenance_work_mem = 32MB
    max_connections = 10
