{
 "title": "bmstu cluster service metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Сервис",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},namespace)"
    }
   },
   { "name": "quantile", "label": "Квантиль", "query": "0.50, 0.95, 0.99" }
  ]
 },
 "panels": [
  { "title": "IdP сервер авторизации", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Время выполнения запроса на токен",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(idp_token_issue_duration_milliseconds_bucket{}[10m])) by (le, client_id, scope, result))",
     "legendFormat": "P$quantile - client={{client_id}} - scope={{scope}} - {{result}}"
    }
   ]
  },
  {
   "title": "Количество выпущенных токенов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(idp_token_issued_total{}[$__rate_interval])) by (client_id, scope, result)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Клиентские запросы авторизации", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Время подписи клиентского запроса токеном",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(client_token_sign_duration_milliseconds_bucket{service_name=\"$namespace\"}[10m])) by (le, enabled, result, scope))",
     "legendFormat": "P$quantile - sign={{enabled}} - scope={{scope}} - {{result}}"
    }
   ]
  },
  {
   "title": "Время выполнения проверки подписи",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(client_token_verify_duration_milliseconds_bucket{service_name=\"$namespace\"}[10m])) by (le, enabled, result, scope))",
     "legendFormat": "P$quantile - verify={{enabled}} - scope={{scope}} - {{result}}"
    }
   ]
  },
  {
   "title": "Количество проверок токена входящих запросов",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(client_token_verify_requests_total{service_name=\"$namespace\"}[$__rate_interval])) by (enabled, scope, result)",
     "legendFormat": " sign={{enabled}} - scope={{scope}} - {{result}}"
    }
   ]
  },
  {
   "title": "Количество подписей запросов токеном",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(client_token_sign_requests_total{service_name=\"$namespace\"}[$__rate_interval])) by (enabled, scope, result)",
     "legendFormat": "verify={{enabled}} - scope={{scope}} - {{result}}"
    }
   ]
  },
  { "title": "Базовые метрики запросов", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Размер HTTP-запросов",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(http_request_size_bytes{service_name=\"$namespace\", quantile=\"$quantile\"}) by (quantile, method, path)",
     "legendFormat": "P$quantile - {{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "Размер HTTP ответов",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(http_response_size_bytes{service_name=\"$namespace\", quantile=\"$quantile\"}) by (quantile, method, path)",
     "legendFormat": "P{{quantile}} - {{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "Длительность HTTP запросов",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(http_request_duration_milliseconds_bucket{service_name=\"$namespace\"}[$__rate_interval])) by (le, method, path))",
     "legendFormat": "P$quantile - {{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "Количество входящих запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_name=\"$namespace\"}[$__rate_interval])) by (method, path, status)",
     "legendFormat": "{{method}} - {{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Длительность запросов к БД",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(db_query_duration_milliseconds_bucket{service_name=\"$namespace\"}[$__rate_interval])) by (le, operation))",
     "legendFormat": "P$quantile - operation={{operation}}"
    }
   ]
  }
 ]
}