apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: postgres-a
data:
  auth-enabled: "false"
  postgresql.conf: |
    listen_addresses = 'localhost'
    port = 5434
    shared_buffers = 128MB
    work_mem = 4MB
    maintenance_work_mem = 32MB
    max_connections = 10
