apiVersion: v1
kind: Service
metadata:
  name: postgres-a
  namespace: postgres-a
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    networking.k8s.io/service-binding: "true"
spec:
  selector:
    app: postgres-a
  ports:
    - name: postgres
      port: 5434
      targetPort: 5434
    - name: sidecar
      port: 8080
      targetPort: 8080
